version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
  node: circleci/node@5
executors:
  aws-executor:
    docker:
      - image: 'cimg/node:20.15.1'
jobs:
  build:
    executor: aws-executor
    steps:
    - checkout
    - run:
          name: 'Build CDK App'
          command: | 
            npm install
            npm run build
