version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
  node: circleci/node@5
  aws-s3: circleci/aws-s3@3.1.1
executors:
  aws-executor:
    docker:
      - image: 'cimg/node:20.15.1'
jobs:
  build:
    executor: aws-executor
    steps:
    - checkout
    - run:
          name: 'Build CDK App'
          command: | 
            npm install
            npm run build
    - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install    
    # - run:
      #     name: Configure AWS CLI
          # command: |
          #   echo "[default]" > ~/.aws/credentials
          #   echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          #   echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
          #   aws configure set region us-east-1 
    - aws-s3/sync: 
          # auth:
          # - aws-cli/setup:
          #       role_arn: arn:aws:iam::590376488337:role/aws-controltower-AdministratorExecutionRole
          from: ./
          to: 's3://pipeline-bucket-mahendra-s3'
          # arguments: | # Optional arguments
          #   --acl public-read
          #   --cache-control "max-age=86400"
   
