version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:20
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build React App
          command: npm run build
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Deploy to S3
          command: |
            aws s3 sync build/ s3://pipeline-bucket-mahendra-s3 --delete
    environment:
      - AWS_ACCESS_KEY_ID: your-aws-access-key-id
      - AWS_SECRET_ACCESS_KEY: your-aws-secret-access-key

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
